import 'dart:convert';

import 'package:apiapp/models/new_ap_model.dart';
import 'package:apiapp/models/product_models.dart';
import 'package:get/get.dart';
import 'package:http/http.dart' as http;

import '../models/api_model.dart';

class APiget extends GetxController {
  Future<List<Autogenerated>> getAPi() async {
    List<Autogenerated> finalresponse = [];

    final response = await http
        .get(Uri.parse('https://www.mocky.io/v2/5dfccffc310000efc8d2c1ad'));
    if (response.statusCode == 200) {
      print(response.statusCode);
      final data = jsonDecode(response.body);

      finalresponse = data.map((json) => Autogenerated.fromJson(json)).toList();
    }
    return finalresponse;
  }
}
